# Dependencies
markdown:         kramdown
highlighter:      rouge
language: 'en-uk'

# Permalinks

# Setup
title:            Dongyul Lee
tagline:          'A Jekyll theme'
description:      'Welcome to Dongyul DNN space'
url:              https://mukaman84.github.io
baseurl:          ''


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mukaman84
